name: Isort Import Formatter for Python
description: Run isort import formatter on whole repository.

runs:
  using: "composite"

  steps:
    - name: Isort
      shell: bash
      run: |
        source .venv/bin/activate
        isort . --check --diff
